


[package]
name = "ctafur-notes"
version = "0.1.0"
authors = ["Carlos E. Tafur Egido"]
license = "MIT"
description = "Template for note taking maths."
entrypoint = "src/template.typ"
compiler = "0.14.2"



[template]
path = "."
entrypoint = "src/template.typ"
# thumbnail = "thumbnail.png"



